/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.PayrollSystem.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.PayrollSystem.Controller.AdministratorController;
import static lk.ijse.PayrollSystem.Controller.AdministratorController.addAdmin;
import lk.ijse.PayrollSystem.Model.AdministratorModel;

/**
 *
 * @author chathu
 */
public class AddAdministrator extends javax.swing.JFrame {

    /**
     * Creates new form AddAdministrator
     */
    public AddAdministrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAdminId = new javax.swing.JTextField();
        txtAdminName = new javax.swing.JTextField();
        txtAdminContact = new javax.swing.JTextField();
        txtAdminUsername = new javax.swing.JTextField();
        txtAdminConPass = new javax.swing.JPasswordField();
        txtAdminPass = new javax.swing.JPasswordField();
        BtnReset = new keeptoo.KButton();
        BtnAddAdmin = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel1.setText("Add Administrator");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Admin Confirm Password   :");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Admin ID  :");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Admin Fullname  :");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Admin Contact  :");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Admin Username  :");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Admin Password   :");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        kGradientPanel1.add(txtAdminId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));
        kGradientPanel1.add(txtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        txtAdminContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminContactActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtAdminContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        txtAdminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminUsernameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));
        kGradientPanel1.add(txtAdminConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, -1));
        kGradientPanel1.add(txtAdminPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, -1));

        BtnReset.setText("Reset");
        kGradientPanel1.add(BtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 30));

        BtnAddAdmin.setText("Add ");
        BtnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddAdminActionPerformed(evt);
            }
        });
        kGradientPanel1.add(BtnAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdminContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminContactActionPerformed

    private void txtAdminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminUsernameActionPerformed

    private void BtnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddAdminActionPerformed
        // TODO add your handling code here:
        String id = txtAdminId.getText();
          String fullname = txtAdminName.getText();
        int contact = Integer.parseInt(txtAdminContact.getText());
        String username = txtAdminUsername.getText();
        String password = txtAdminPass.getText();
        String conpass = txtAdminConPass.getText();

        if (conpass.equals(password)) {

            if ( txtAdminId.getText().equals("") ||txtAdminName.getText().equals("") || txtAdminContact.getText().equals("")
                    || txtAdminUsername.getText().equals("") || txtAdminPass.getText().equals("") || txtAdminConPass.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "missing feilds");
            } else {

                AdministratorModel admin = new AdministratorModel( id, fullname,  contact, username, password);

                  try {
                    boolean isAdded = AdministratorController.addAdmin(admin);

                    if (isAdded) {
                        JOptionPane.showMessageDialog(this, "Added Success");
                    } else {
                        JOptionPane.showMessageDialog(this, "Added Fail");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AddAdministrator.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddAdministrator.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        }
        else{ 
            JOptionPane.showMessageDialog(this, "passwords dont match");
        }
        
    }//GEN-LAST:event_BtnAddAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton BtnAddAdmin;
    private keeptoo.KButton BtnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtAdminConPass;
    private javax.swing.JTextField txtAdminContact;
    private javax.swing.JTextField txtAdminId;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JPasswordField txtAdminPass;
    private javax.swing.JTextField txtAdminUsername;
    // End of variables declaration//GEN-END:variables
}
