/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.PayrollSystem.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.PayrollSystem.Controller.EmployeeController;
import lk.ijse.PayrollSystem.Model.EmployeeModel;

/**
 *
 * @author chathu
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmpId = new javax.swing.JTextField();
        txtEmpname = new javax.swing.JTextField();
        txtEmpContact = new javax.swing.JTextField();
        txtEmpBasicSalary = new javax.swing.JTextField();
        BtnResetEmp = new keeptoo.KButton();
        BtnAddEmp = new keeptoo.KButton();
        txtEmpRole = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel1.setText("Add Employee");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Employee ID  :");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Employee Fullname  :");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Employee Contact  :");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Role :");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Basic Salary :");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        kGradientPanel1.add(txtEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));
        kGradientPanel1.add(txtEmpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        txtEmpContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpContactActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtEmpContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        txtEmpBasicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpBasicSalaryActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtEmpBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, -1));

        BtnResetEmp.setText("Reset");
        kGradientPanel1.add(BtnResetEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 30));

        BtnAddEmp.setText("Add ");
        BtnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddEmpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(BtnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 100, 30));

        txtEmpRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpRoleActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtEmpRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpContactActionPerformed

    private void txtEmpBasicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpBasicSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpBasicSalaryActionPerformed

    private void BtnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddEmpActionPerformed
        // TODO add your handling code here:
        String id = txtEmpId.getText();
        String fullname = txtEmpname.getText();
        int contact = Integer.parseInt(txtEmpContact.getText());
         String role =txtEmpRole.getText();
        Double BasicSal = Double.parseDouble(txtEmpBasicSalary.getText());
       

        

            if ( txtEmpId.getText().equals("") ||txtEmpname.getText().equals("") || txtEmpContact.getText().equals("")
                || txtEmpBasicSalary.getText().equals("") || txtEmpRole.getText().equals("") ) {
                JOptionPane.showMessageDialog(this, "missing feilds");
            } else {

                EmployeeModel employee = new EmployeeModel( id, fullname,  contact,role,BasicSal );

                boolean isAdded;
            try {
                isAdded = EmployeeController.addEmployee(employee);
                 if (isAdded) {
                    JOptionPane.showMessageDialog(this, "Added Success");
                } else {
                    JOptionPane.showMessageDialog(this, "Added Fail");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
    }//GEN-LAST:event_BtnAddEmpActionPerformed

    private void txtEmpRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton BtnAddEmp;
    private keeptoo.KButton BtnResetEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtEmpBasicSalary;
    private javax.swing.JTextField txtEmpContact;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtEmpRole;
    private javax.swing.JTextField txtEmpname;
    // End of variables declaration//GEN-END:variables
}
